{% set name = "gemseo" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17d4e5f2c78a87067f2667ce0c8ce634bee77b8156d214a0dbf0fbf9eeef5b35

build:
  skip: true  # [py>=311]
  entry_points:
    - gemseo-study = gemseo.utils.study_analyses.study_analysis_cli:main
    - gemseo-deserialize-run = gemseo.utils.deserialize_and_run:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docstring-inheritance >=1.0.0,<=2.0.1
    - python-fastjsonschema >=2.14.5,<=2.18.0
    - genson ==1.2.2
    - h5py >=3.0.0,<=3.9.0
    - jinja2 >=3.0.0,<=3.1.2
    - matplotlib-base >=3.3.0,<=3.8.0
    - networkx >=2.2,<=3.1
    - numpy >=1.21,<=1.26.0
    - packaging <=23.1
    - pandas >=1.1.0,<=2.1.1
    - pyxdsm >=2.1.0,<=2.3.0
    - pydantic >=1.10.8,<2
    - requests
    - scipy >=1.4,<=1.10.1
    - strenum >=0.4.9,<=0.4.15
    - tqdm >=4.41,<=4.66.1
    - typing-extensions >=4,<5
    - xdsmjs >=1.0.0,<=2.0.0
    - python-xxhash >=3.0.0,<=3.3.0
# Extra: all
    - python-graphviz >=0.16,<=0.20.1
    - nlopt >=2.7.0,<=2.7.1
    - openpyxl <=3.1.2
    - openturns >=1.16,<=1.21
    - pydoe2 >=1.0.2,<=1.3.0
    - scikit-learn >=0.18,<=1.3.1
    - sympy >=1.5,<=1.12
    - xlwings >=0.27.0,<=0.27.15  # [win]
    - pillow >=9.5.0,<=10.0.1

test:
  imports:
    - gemseo
  commands:
    # Fails because python-xxhash has bad pip version.
    # - pip check
    - gemseo-study --help
  requires:
    - pip

about:
  home: https://gitlab.com/gemseo
  summary: Generic Engine for Multi-disciplinary Scenarios, Exploration and Optimization
  dev_url: https://gitlab.com/gemseo/dev/gemseo
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
