{% set name = "gemseo" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gemseo-{{ version }}.tar.gz
  sha256: cfda7d0015fb1fb60b5baf8fcdbc2c88c2bc9527ac4932cc303428764fe2aa33

build:
  number: 0
  entry_points:
    - gemseo-study = gemseo.utils.study_analysis_cli:main
    - gemseo-template-grammar-editor = gemseo.wrappers.template_grammar_editor:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
  run:
    - docstring-inheritance ==1.0.0
    - genson ==1.2.2
    - h5py >=2.3,<=3.6.0
    - importlib_metadata  # [py==37]
    - jinja2 <=3.1.2
    - matplotlib-base >=2,<=3.5.2
    - networkx >=2.2,<=2.8.5
    - nlopt >=2.4.2,<=2.7.1
    - numpy >=1.10,<=1.23.1
    - openpyxl <=3.0.10
    - openturns >=1.16,<=1.18
    - packaging <=21.3
    - pandas >=0.16,<=1.4.3
    - pdfo >=1.0.0,<=1.2
    - pydoe2 >=0.3.8,<=1.3.0
    - pyside2
    - python
    - python-graphviz >=0.16,<=0.20
    - python-fastjsonschema <=2.16.1
    - python-xxhash ==3.0.0
    - pyxdsm <=2.2.1
    - requests
    - scikit-learn >=0.18,<=1.1.1
    - scipy >=1.1,<=1.7.3
    - singledispatchmethod  # [py==37]
    - sympy >=0.7,<=1.10.1
    - tqdm >=4.41,<=4.64.0
    - typing-extensions >=4,<5
    - xdsmjs >=1.0.0,<=1.0.1
    - xlwings ==0.27.*  # [win]

test:
  imports:
    - gemseo
  commands:
    # Fails because python-xxhash has bad pip version.
    # - pip check
    - gemseo-study --help
  requires:
    - pip

about:
  home: https://gitlab.com/gemseo
  summary: Generic Engine for Multi-disciplinary Scenarios, Exploration and Optimization
  dev_url: https://gitlab.com/gemseo/dev/gemseo
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
