{% set name = "gemseo" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gemseo-{{ version }}.tar.gz
  sha256: f23fcff28928c10e35f22688baa45bb467a7c9d8ee3afb50518e5e4462a67cc2

build:
  skip: true  # [py>=311]
  entry_points:
    - gemseo-study = gemseo.utils.study_analysis_cli:main
    - gemseo-template-grammar-editor = gemseo.wrappers.template_grammar_editor:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docstring-inheritance ==1.0.0
    - python-fastjsonschema >=2.14.5,<=2.16.2
    - genson ==1.2.2
    - h5py >=3.0.0,<=3.7.0
    - importlib-metadata <5  # [py==37]
    - jinja2 >=3.0.0,<=3.1.2
    - matplotlib-base >=3.3.0,<=3.6.2
    - networkx >=2.2,<=2.8.8
    - numpy >=1.21,<=1.23.4
    - packaging <=21.3
    - pandas >=1.1.0,<=1.5.1
    - pyxdsm >=2.1.0,<=2.2.2
    - requests
    - scipy >=1.4,<=1.9.1
    - singledispatchmethod ==1.0  # [py==37]
    - tqdm >=4.41,<=4.64.1
    - typing-extensions >=4,<5
    - xdsmjs >=1.0.0,<=1.0.1
    - python-xxhash >=3.0.0,<=3.1.0  # 
# Extra: all
    - python-graphviz >=0.16,<=0.20.1
    - nlopt >=2.7.0,<=2.7.1
    - openpyxl <=3.0.10
    - openturns >=1.16,<=1.19
    - pdfo >=1.0.0,<=1.2
    - pydoe2 >=1.0.2,<=1.3.0
    - pyside2
    - scikit-learn >=0.18,<=1.1.3
    - sympy >=1.5,<=1.11.1
    - xlwings >=0.27.0,<=0.27.15  # [win]

test:
  imports:
    - gemseo
  commands:
    # Fails because python-xxhash has bad pip version.
    # - pip check
    - gemseo-study --help
  requires:
    - pip

about:
  home: https://gitlab.com/gemseo
  summary: Generic Engine for Multi-disciplinary Scenarios, Exploration and Optimization
  dev_url: https://gitlab.com/gemseo/dev/gemseo
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
