{% set name = "gemseo" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gemseo-{{ version }}.tar.gz
  sha256: 884123d6bdf15539d78977a8564a45c08e4903a5c07ad17485eaf8c52393b63e

build:
  number: 0
  skip: true  # [py>=310]
  entry_points:
    - gemseo-study = gemseo.utils.study_analysis_cli:main
    - gemseo-template-grammar-editor = gemseo.wrappers.template_grammar_editor:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python  # [py==36 or py==37 or py==38 or py==39]
  run:
    - custom-inherit ==2.4.0
    - python-fastjsonschema <=2.15.1
    - future
    - genson ==1.2.2
    - h5py >=2.3,<=3.2.1
    - importlib_metadata  # [py<38]
    - jinja2 <=3.0.1
    - matplotlib-base >=2,<=3.4.3
    - networkx >=2.2,<=2.5
    - numpy >=1.10,<=1.20.3
    - packaging <=21.3
    - python  # [py==36 or py==37 or py==38 or py==39]
    - pyxdsm <=2.2.0
    - requests
    - scipy >=1.1,<=1.7.1
    - six
    - tqdm >=4.41,<=4.61.0
    - xdsmjs >=1.0.0,<=1.0.1
    - nlopt >=2.4.2,<=2.7.0
    - openturns >=1.13,<=1.18
    - pandas >=0.16,<=1.3.4
    - pydoe2 >=0.3.8,<=1.3.0
    - pyside2 <=5.15.2
    - scikit-learn >=0.18,<=1.0.1
    - sympy >=0.7,<=1.9
    - openpyxl <=3.0.7
    - xlwings <=0.21.4  # [win]
    - python-graphviz ==0.16
    - pdfo ==1.0.0
    - python-xxhash ==3.0.0

test:
  imports:
    - gemseo
  commands:
    - pip check
    - gemseo-study --help
  requires:
    - pip

about:
  home: https://gitlab.com/gemseo
  summary: Generic Engine for Multi-disciplinary Scenarios, Exploration and Optimization
  dev_url: https://gitlab.com/gemseo/dev/gemseo
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
